# Copyright 2010 David Roundy, roundyd@physics.oregonstate.edu.
# All rights reserved.

include $(GOROOT)/src/Make.inc

TARG=github.com/droundy/go/x86

GOFILES=\
	x86.go\
	debugging.go\

include $(GOROOT)/src/Make.pkg
